# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Nothin'
author: Abimereki Muzaale
logo: practicing.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - bibliography.bib

# Add the following lines to enable back-references
bibtex:
  backrefs: true  # Show backreferences in the bibliography
  bibtex_use_backref: true  # Show backreferences in the bibliography

# Use author-year citations
jupyterbook:
  citation_reference_template: "[{{ order }}]"

# Specify the template for the full citation in the bibliography
bibliography_item_template: "{{ order }}. {{ details.authors }}. {{ details.title }}. {{ details.year }}. {% if details.url %}URL: {{ details.url }}.{% endif %}"

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# Do not include in the build any files matching these patterns
exclude_patterns: [pattern1/*, path/to/myfile.ipynb]
